// GENERATED by scripts/gen-known-labels.js — do not edit by hand.
// Baked-in confirmed human-review labels (data/fingerprint/human-decisions.json).
globalThis.__BIPU_KNOWN_LABELS__ = {
  "lilchiva": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "human I've interested with"
  },
  "almostmedia": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "She's human"
  },
  "garcia590": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "garcia is a human focused on crypto research"
  },
  "steph_curdy": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "Human, have had calls with him"
  },
  "memefortrees": {
    "behavioral": "confirm",
    "intent": "good",
    "reason": "Had a call, they set up an endowment for BIPU that will get fed over time via the memes being shared."
  },
  "boardyai": {
    "behavioral": "confirm",
    "intent": "good",
    "reason": "Boardy is a helpful and good bot"
  },
  "1720665183188922368": {
    "behavioral": "confirm",
    "intent": "good",
    "reason": "looks like a response from grok"
  },
  "alchemicav": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "He's human. We've had a call and I know him"
  },
  "shadow_rebbe": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "Human, have done some work with"
  },
  "jessyka_boat": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "Jessyka is fully human"
  },
  "aikun011": {
    "behavioral": "reject",
    "intent": "neutral",
    "reason": "looks human"
  }
};
